name: Code Collection CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Prerequisite
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - name: Code Collection Test
        run: |
          cd STO && go test && cd ..
          cd Go-pattern &&  go test ./... && cd ..